palette = "catppuccin_macchiato"
format = """
[░▒▓](rosewater)\
[  ](bg:rosewater fg:surface0)\
[](bg:pink fg:rosewater)\
$directory\
[](fg:pink bg:blue)\
$git_branch\
$git_status\
[](fg:blue bg:lavender)\
$nodejs\
$rust\
$golang\
$php\
[](fg:lavender bg:surface0)\
$time\
[ ](fg:surface0)\
\n$character"""

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[directory]
style = "fg:surface1 bg:pink"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol $branch ](fg:surface1 bg:blue)]($style)'

[git_status]
style = "bg:lavender"
format = '[[($all_status$ahead_behind )](fg:surface1 bg:blue)]($style)'

[nodejs]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol ($version) ](fg:base bg:lavender)]($style)'

[rust]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol ($version) ](fg:base bg:lavender)]($style)'

[golang]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol ($version) ](fg:base bg:lavender)]($style)'

[php]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol ($version) ](fg:base bg:lavender)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:surface0"
format = '[[  $time ](fg:text bg:surface0)]($style)'

